### PR TITLE
Update all emails to be @cascadiafest.org

### PR DESCRIPTION
**Pull request by jemjam**
Saw a mention in #volunteering (via slack) that this was a quick thing someone could help with. If that's helpful, here you go @davethegr8 
- Change all emails from @cascadiajs.com to @cascadiafest.org

### CODE REVIEW

**Comment by davethegr8** [comment]
Awesome, thanks!

A couple of items:
- I need to confirm that the carter and tracy emails were migrated before merging this
- Also, if you want, please add yourself under the contributors block in `staff/_data.json` If should look like this:

```
your_github_username: {
    username: your_github_username,
    avatar: your_gh_avatar_url
}
```

I can fill in the avatar url if needed.

**Comment by jemjam** [comment]
Oh great, good call. I'll add those to this commit.

I can easily revert Carter/Tracy's emails too, I just did a search project wide to sort this.

**Comment by davethegr8** [comment]
hey @JemBijoux - I got official word we need to keep carter & tracy's emails @cascadiajs for now. Can you reverse those?

**Comment by jemjam** [comment]
Sure thing!

**Pull request merged**
